routes/web.php
<?php


use App\Booking;
use App\FixBooking;
use Hekmatinasser\Verta\Verta;

Route::get('/playground', function () {




});

Auth::routes();

Route::get('/', function () {
    return redirect()->route('admin.dashboard.index');
});

Route::middleware(['auth', 'admin'])->prefix('admin')->group(function () {


    Route::get('dashboard', 'Admin\DashboardController@index')->name('admin.dashboard.index');

    Route::get('clubs', 'Admin\ClubsController@index')->name('admin.clubs.index');
    Route::get('clubs/create', 'Admin\ClubsController@create')->name('admin.clubs.create');
    Route::get('clubs/{club}/edit', 'Admin\ClubsController@edit')->name('admin.clubs.edit');
    Route::post('clubs', 'Admin\ClubsController@store')->name('admin.clubs.store');
    Route::patch('clubs/{club}', 'Admin\ClubsController@update')->name('admin.clubs.update');
    Route::delete('clubs/{club}', 'Admin\ClubsController@delete')->name('admin.clubs.delete');

    Route::get('clubs/{club}/courts', 'Admin\CourtsController@index')->name('admin.courts.index');
    Route::get('clubs/{club}/courts/create', 'Admin\CourtsController@create')->name('admin.courts.create');
    Route::get('clubs/{club}/courts/{court}/edit', 'Admin\CourtsController@edit')->name('admin.courts.edit');
    Route::get('clubs/{club}/courts/{court}', 'Admin\CourtsController@delete')->name('admin.courts.delete');
    Route::post('clubs/{club}/courts', 'Admin\CourtsController@store')->name('admin.courts.store');
    Route::patch('clubs/{club}/courts/{court}', 'Admin\CourtsController@update')->name('admin.courts.update');

    Route::get('bookings', 'Admin\BookingsController@index')->name('admin.bookings.index');
    Route::get('bookings/fixes', 'Admin\BookingsController@addFixBookings')->name('admin.bookings.add_fixes');
    Route::get('bookings/canceled', 'Admin\BookingsController@canceled')->name('admin.bookings.canceled');
    Route::get('bookings/{booking}/cancel/is-valid-time', 'Admin\BookingsController@isValidTimeForCanceling')->name('admin.bookings.isValidTimeForCanceling');
    Route::post('bookings', 'Admin\BookingsController@store')->name('admin.bookings.store');
    Route::patch('bookings/{booking}/cancel', 'Admin\BookingsController@cancel')->name('admin.bookings.cancel');
    Route::patch('bookings/{booking}/pay', 'Admin\BookingsController@pay')->name('admin.bookings.pay');
    Route::delete('bookings/{booking}/delete', 'Admin\BookingsController@delete')->name('admin.bookings.delete');

    Route::get('ajax/coaches', 'Admin\CoachesController@getCoaches')->name('admin.coaches.getCoaches');
    Route::get('ajax/coach/bookings', 'Admin\CoachesController@getBookings')->name('admin.coaches.getBookings');

    Route::get('bookings/part-time/{partTimeBooking}/cancel/is-valid-time', 'Admin\PartTimeBookingsController@isValidTimeForPartTimeCanceling')->name('admin.bookings.isValidTimeForPartTimeCanceling');
    Route::post('bookings/{booking}/part-time', 'Admin\PartTimeBookingsController@store')->name('admin.bookings.part_time.store');
    Route::patch('bookings/{partTimeBooking}/part-time/pay', 'Admin\PartTimeBookingsController@pay')->name('admin.bookings.part_time.pay');
    Route::patch('bookings/{partTimeBooking}/part-time/cancel', 'Admin\PartTimeBookingsController@cancel')->name('admin.bookings.part_time.cancel');
    Route::delete('bookings/{partTimeBooking}/part-time/delete', 'Admin\PartTimeBookingsController@delete')->name('admin.bookings.part_time.delete');


    Route::get('hours/bookings', 'Admin\HoursBookingsController@index')->name('admin.hours_bookings.index');
    Route::post('hours/bookings', 'Admin\HoursBookingsController@store')->name('admin.hours_bookings.store');

    Route::get('fix/bookings', 'Admin\FixBookingsController@index')->name('admin.fix_bookings.index');
    Route::get('fix/bookings/create', 'Admin\FixBookingsController@create')->name('admin.fix_bookings.create');
    Route::get('fix/bookings/{fixBooking}/edit', 'Admin\FixBookingsController@edit')->name('admin.fix_bookings.edit');
    Route::get('fix/bookings/{fixBooking}/delete', 'Admin\FixBookingsController@delete')->name('admin.fix_bookings.delete');
    Route::post('fix/bookings', 'Admin\FixBookingsController@store')->name('admin.fix_bookings.store');
    Route::patch('fix/bookings/{fixBooking}', 'Admin\FixBookingsController@update')->name('admin.fix_bookings.update');


    Route::get('ajax/activity/date-time/dates', 'Admin\ActivityDateAndTimeController@dates');
    Route::get('ajax/activity/date-time/hours', 'Admin\ActivityDateAndTimeController@hours');


    Route::get('ajax/booking/note', 'Admin\BookingNoteController@index');
    Route::post('ajax/booking/note', 'Admin\BookingNoteController@store');

    Route::get('ajax/courts', 'Admin\CourtsController@courts');


    Route::get('ajax/court/bookings', 'Admin\BookingsController@getCourtBookings')->name('admin.bookings.getCourtBookings');


    Route::get('coaches', 'Admin\CoachesController@index')->name('admin.coaches.index');
    Route::get('coaches/create', 'Admin\CoachesController@create')->name('admin.coaches.create');
    Route::get('coaches/{coach}/edit', 'Admin\CoachesController@edit')->name('admin.coaches.edit');
    Route::get('coaches/{coach}/delete', 'Admin\CoachesController@delete')->name('admin.coaches.delete');
    Route::post('coaches', 'Admin\CoachesController@store')->name('admin.coaches.store');
    Route::patch('coaches/{coach}', 'Admin\CoachesController@update')->name('admin.coaches.update');

    Route::get('financial/creditors', 'Admin\FinancialController@creditors')->name('admin.creditors.index');
    Route::get('financial/coaches/debt', 'Admin\FinancialController@coachesDebtList')->name('admin.financial.coaches_debt_list');
    Route::get('financial/coaches/{coach}/pay', 'Admin\FinancialController@coachPayForm')->name('admin.financial.coach_pay_form');
    Route::patch('financial/coaches/{coach}/pay', 'Admin\FinancialController@storeCoachPay')->name('admin.financial.coach_pay');
    Route::get('financial/debtors', 'Admin\FinancialController@debtors')->name('admin.debtors.index');
    Route::patch('financial/creditors/{creditor}/refund', 'Admin\FinancialController@refundCreditorMoney')->name('admin.refund_creditors.index');
    Route::patch('financial/debtors/{debtor}/pay', 'Admin\FinancialController@debtorPaid')->name('admin.debtor_pay.index');

    Route::get('financial/players/debt', 'Admin\FinancialController@playersDebtList')->name('admin.financial.players_debt_list');
    Route::get('financial/players/{player}/pay', 'Admin\FinancialController@playerPayForm')->name('admin.financial.player_pay_form');
    Route::get('financial/players/{player}/sync-balance', 'Admin\FinancialController@syncPlayerBalance')->name('admin.financial.sync_player_balance');
    Route::patch('financial/players/{player}/pay', 'Admin\FinancialController@storePlayerPay')->name('admin.financial.player_pay');
    Route::patch('financial/players/{player}/edit-lessons-pay', 'Admin\FinancialController@reducePlayerBalance')->name('admin.financial.edit_lessons_pay');

    Route::get('statistic/bookings', 'Admin\StatisticsController@bookings')->name('admin.statistics.bookings');
    Route::get('statistic/canceled', 'Admin\StatisticsController@canceled')->name('admin.statistics.canceled');

    Route::get('ajax/statistic/revenue/weekly', 'Admin\StatisticsController@revenueWeekly');
    Route::get('ajax/statistic/revenue/monthly', 'Admin\StatisticsController@revenueMonthly');
    Route::get('ajax/statistic/revenue/annually', 'Admin\StatisticsController@revenueAnnually');

    Route::get('ajax/statistic/bookings/weekly', 'Admin\StatisticsController@bookingsWeekly');
    Route::get('ajax/statistic/bookings/monthly', 'Admin\StatisticsController@bookingsMonthly');
    Route::get('ajax/statistic/bookings/annually', 'Admin\StatisticsController@bookingsAnnually');

    Route::get('ajax/statistic/canceled/weekly', 'Admin\StatisticsController@canceledWeekly');
    Route::get('ajax/statistic/canceled/monthly', 'Admin\StatisticsController@canceledMonthly');
    Route::get('ajax/statistic/canceled/annually', 'Admin\StatisticsController@canceledAnnually');

    Route::get('players', 'Admin\PlayersController@index')->name('admin.players.index');
    Route::get('players/{player}/profile', 'Admin\PlayersController@profile')->name('admin.players.profile');
    Route::get('players/create', 'Admin\PlayersController@create')->name('admin.players.create');
    Route::get('players/{player}/edit', 'Admin\PlayersController@edit')->name('admin.players.edit');
    Route::get('players/{player}/delete', 'Admin\PlayersController@delete')->name('admin.players.delete');
    Route::post('players/store', 'Admin\PlayersController@store')->name('admin.players.store');
    Route::patch('players/{player}/update', 'Admin\PlayersController@update')->name('admin.players.update');


    Route::get('got-to-date', function () {
        $d = request('d');
        $n = request('n');
        $y = request('y');

        $date = "{$y}-${n}-${d}";

        return redirect('/admin/bookings/?date=' . $date);
    })->name('go.to.date');

});

app/Coach.php
<?php

namespace App;

use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Model;

class Coach extends Model
{
    protected $guarded = [];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function bookings()
    {
        return $this->hasMany(Booking::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function partTimeBookings()
    {
        return $this->hasMany(PartTimeBooking::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function debt()
    {
        return $this->hasMany(Debtor::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function credit()
    {
        return $this->hasMany(Creditor::class);
    }

    /**
     * @return int|mixed
     */
    public function deptLessonMinutes()
    {

        $bookingMinutes = $this->bookings()
            ->where('is_canceled', '=', false)
            ->where('is_paid', '=', false)
            ->sum('duration');

        $partTimeBookingMinutes = $this->partTimeBookings()
            ->where('is_canceled', '=', false)
            ->where('is_paid', '=', false)
            ->sum('duration');

        return $partTimeBookingMinutes + $bookingMinutes;

    }

    /**
     * @return int|mixed
     */
    public function deptLessonCount()
    {

        $bookingMinutes = $this->bookings()
            ->where('is_canceled', '=', false)
            ->where('is_paid', '=', false)
            ->count();

        $partTimeBookingMinutes = $this->partTimeBookings()
            ->where('is_canceled', '=', false)
            ->where('is_paid', '=', false)
            ->count();

        return $partTimeBookingMinutes + $bookingMinutes;

    }

    /**
     * @return int|mixed
     */
    public function todayLessonHours()
    {
        return $this->bookings()->where('date', Verta::now()->format('Y-n-j'))->where('is_canceled',false)->count();
    }

    public function totalLearningCount(){

        $bookingMinutes = $this->bookings()
            ->where('is_canceled', '=', false)
            ->count();

        $partTimeBookingMinutes = $this->partTimeBookings()
            ->where('is_canceled', '=', false)
            ->count();

        return $partTimeBookingMinutes + $bookingMinutes;

    }

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

}

app/FixBooking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FixBooking extends Model
{

    protected $guarded = [];

    protected $appends = ['court_name', 'coach_name'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function court()
    {
        return $this->belongsTo(Court::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function coach()
    {
        return $this->belongsTo(Coach::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function player(){
        return $this->belongsTo(Player::class);
    }

    /**
     * @return string
     */
    public function getCoachNameAttribute()
    {
        if($this->coach){
            return $this->coach->first_name . ' ' . $this->coach->last_name;
        }
    }

    /**
     * @return mixed
     */
    public function getCourtNameAttribute()
    {
        return $this->court->name;
    }
}

app/Http/Controllers/Admin/FixBookingsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Club;
use App\Coach;
use App\FixBooking;
use App\Http\Controllers\Controller;
use Hekmatinasser\Verta\Verta;
use Illuminate\Http\Request;

class FixBookingsController extends Controller
{

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {

        $day = \request('day');

        if ($day) {
            $fixBookings = FixBooking::where('day', $day)->paginate(50);
        }else{
            $fixBookings = FixBooking::paginate(50);
        }

        return view('admin.fix_bookings.index', compact('fixBookings'));
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {

        $club = Club::first();

        $courts = $club->courts;

        $openingHours = $club->openingHours();

        return view('admin.fix_bookings.create', compact('openingHours', 'courts'));
    }

    /**
     * @param FixBooking $fixBooking
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(FixBooking $fixBooking)
    {


        $club = Club::first();

        $courts = $club->courts;

        $openingHours = $club->openingHours();

        return view('admin.fix_bookings.edit', compact('fixBooking', 'openingHours', 'courts'));
    }

    /**
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $data = $this->getValidateDate();

        if ($this->isBooked()) {

            if (\request()->wantsJson()) {
                return response()->json(['msg' => 'در این روز و ساعت رزرو فیکسی دیگری است.'], 422);
            }

            flash('در این روز و ساعت رزرو فیکسی دیگری است.', 'danger');

            return back();
        }

        $booked = FixBooking::create($data);

        if (\request()->wantsJson()) {
            return response()->json(['msg' => 'رزرو فیکسی با موفقیت ذخیره شد', 'booked' => $booked]);
        }

        flash('رزرو با موفقیت ثبت شد', 'success');

        return redirect()->route('admin.fix_bookings.index');
    }

    /**
     * @param FixBooking $fixBooking
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(FixBooking $fixBooking)
    {

        $data = $this->getValidateDate();

        if ($this->isCurrentFixBooked($fixBooking)) {

            $fixBooking->update($data);

        } else {

            if ($this->isBooked()) {
                flash('در این روز و ساعت رزرو فیکسی دیگری است.', 'danger');

                return back();
            }


            $fixBooking->update($data);

        }


        flash('رزرو با موفقیت ویرایش شد', 'success');

        return redirect()->route('admin.fix_bookings.index');

    }

    /**
     * @param FixBooking $fixBooking
     *
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function delete(FixBooking $fixBooking)
    {

        $fixBooking->delete();

        flash('رزرو با موفقیت حذف شد', 'success');

        return redirect()->route('admin.fix_bookings.index');

    }

    /**
     * @return array
     */
    private function getValidateDate(): array
    {
        $data = \request()->validate([
            'court_id' => 'required',
            'renter_name' => 'required_without:coach_id',
            'coach_id' => 'required_without:renter_name',
            'day' => 'required',
            'time' => 'required',
            'partner_name' => 'nullable',
            'player_id' => 'nullable',
        ]);

        return $data;
    }

    /**
     * @return mixed
     */
    private function isBooked()
    {
        return FixBooking::where('day', \request()->input('day'))
            ->where('time', \request()->input('time'))
            ->where('court_id', \request()->input('court_id'))
            ->first();
    }

    /**
     * @param FixBooking $fixBooking
     *
     * @return bool
     */
    private function isCurrentFixBooked(FixBooking $fixBooking): bool
    {
        return $fixBooking->day === \request()->input('day') && $fixBooking->time === \request()->input('time') && $fixBooking->court_id === \request()->input('court_id');
    }
}

resources/views/admin/fix_bookings/_form.blade.php
<div class="form-group">
    <label>کورت</label>
    <select name="court_id" class="form-control">
        @foreach($courts as $court)
            <option value="{{$court->id}}"
                {{$court->id === $fixBooking->court_id ? 'selected' : ''}}>{{$court->name}}</option>
        @endforeach
    </select>
</div>

<div class="form-group">
    <label>نام رزرو کننده</label>
    <input name="renter_name"
           type="text"
           class="form-control"
           value="{{old('renter_name') ?? $fixBooking->renter_name}}">
    @component('components.validation',['field' => 'renter_name'])
    @endcomponent
</div>

<div class="form-group">
    <lavel>نام مربی</lavel>
    <select name="coach_id" id="" class="form-control">
        @foreach(\App\Coach::all() as $coach)
            <option {{$coach->id === $fixBooking->coach->id ? 'selected' : ''}} value="{{$coach->id}}">{{$coach->first_name}} {{$coach->last_name}}</option>
        @endforeach
    </select>
    @component('components.validation',['field' => 'coach_id'])
    @endcomponent
</div>

<div class="form-group">
    <label>نام شاگرد</label>
    <select name="player_id" class="form-control">
        @foreach(\App\Player::all() as $player)
            <option {{$player->id === $fixBooking->player->id ? 'selected' : ''}} value="{{$player->id}}">
                {{ $player->first_name . ' ' . $player->last_name }}
            </option>
        @endforeach
    </select>
    @component('components.validation',['field' => 'player_id'])
    @endcomponent
</div>

<div class="form-group">
    <label>روز هفته</label>
    <select name="day" id="day" class="form-control">
        <option value="شنبه" {{$fixBooking->day === 'شنبه' ? 'selected' : ''}}>شنبه</option>
        <option value="یکشنبه" {{$fixBooking->day === 'یکشنبه' ? 'selected' : ''}}>یکشنبه</option>
        <option value="دوشنبه" {{$fixBooking->day === 'دوشنبه' ? 'selected' : ''}}>دوشنبه</option>
        <option value="سه شنبه" {{$fixBooking->day === 'سه شنبه' ? 'selected' : ''}}>سه شنبه</option>
        <option value="چهارشنبه" {{$fixBooking->day === 'چهارشنبه' ? 'selected' : ''}}>چهارشنبه</option>
        <option value="پنج شنبه" {{$fixBooking->day === 'پنج شنبه' ? 'selected' : ''}}>پنج شنبه</option>
        <option value="جمعه" {{$fixBooking->day === 'جمعه' ? 'selected' : ''}}>جمعه</option>
    </select>
    @component('components.validation',['field' => 'day'])
    @endcomponent
</div>

<div class="form-group">
    <label>ساعت</label>
    <select name="time" id="time" class="form-control">
        @foreach($openingHours as $hour)
            <option value="{{$hour}}" {{$fixBooking->time === $hour ? 'selected' : ''}}>@faNum($hour,false)</option>
        @endforeach
    </select>
    @component('components.validation',['field' => 'time'])
    @endcomponent
</div>


<div class="form-group">
    <button class="btn btn-success">ذخیره</button>
</div>

resources/views/admin/fix_bookings/create.blade.php
@extends('layouts.app_admin')


@section('content')

    <a href="{{route('admin.fix_bookings.index')}}" class="btn btn-light btn-elevate mb-3">بازگشت</a>

    <div class="row">
        <div class="col-md-6">
            @component('components.portletWithoutFooter',['title' => 'رزرو فیکسی'])
                <fix-booking :courts="{{json_encode($courts)}}"
                             :players="{{json_encode(\App\Player::all())}}"
                             :hours="{{json_encode($openingHours)}}"
                             :coaches="{{json_encode(\App\Coach::all())}}"></fix-booking>
            @endcomponent
        </div>
        <div class="col-md-6">
            @component('components.portletWithoutFooter',['title' => 'فیکسی ها'])
                <fix-list></fix-list>
            @endcomponent
        </div>
    </div>

@endsection

resources/views/admin/fix_bookings/edit.blade.php
@extends('layouts.app_admin')


@section('content')

    <a href="{{route('admin.fix_bookings.index')}}" class="btn btn-light btn-elevate mb-3">بازگشت</a>

    <div class="row">
        <div class="col-md-6">
            @component('components.portletWithoutFooter',['title' => 'رزرو فیکسی'])
                <form class="kt-form" action="{{route('admin.fix_bookings.update',$fixBooking)}}" method="POST">
                    @csrf
                    @method('PATCH')
                    @include('admin.fix_bookings._form')
                </form>
            @endcomponent
        </div>
    </div>

@endsection

resources/views/admin/fix_bookings/index.blade.php
@extends('layouts.app_admin')


@section('content')

    <a href="{{route('admin.fix_bookings.create')}}" class="btn btn-light btn-elevate mb-3">اضافه کردن</a>

    @component('components.portletWithoutFooter',['title' => 'نمایش با روز هفته'])
        <form action="{{route('admin.fix_bookings.index')}}">
            <div class="form-group">
            <select name="day" id="day" class="form-control">
                <option value="شنبه">شنبه</option>
                <option value="یکشنبه">یکشنبه</option>
                <option value="دوشنبه">دوشنبه</option>
                <option value="سه شنبه">سه شنبه</option>
                <option value="چهارشنبه">چهارشنبه</option>
                <option value="پنج شنبه">پنج شنبه</option>
                <option value="جمعه">جمعه</option>
            </select>
            </div>
            <div class="form-group">
                <button type="submit" class="btn-sm btn btn-success">نمایش</button>
            </div>
        </form>
    @endcomponent

    @component('components.portletWithoutFooter',['title' => 'لیست فیکسی'])

        <table class="table table-bordered table-hover" id="datatbl">
            <thead>
            <tr>
                <th scope="col">رزرو کننده</th>
                <th scope="col">روز</th>
                <th scope="col">ساعت</th>
                <th scope="col">نام پارتنر</th>
                <th scope="col">عملیات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($fixBookings as $fix)
                <tr>
                    <td>{{$fix->coach_id ? $fix->coach->full_name : $fix->renter_name}}</td>
                    <td>{{$fix->day}}</td>
                    <td>@faNum($fix->time,false)</td>
                    <td>{{$fix->partner_name ?? '-'}}</td>
                    <td>
                        <a href="{{route('admin.fix_bookings.edit',$fix)}}"
                           class="btn btn-sm btn-clean btn-icon btn-icon-md" title="ویرایش">
                            <i class="la la-edit text-success"></i>
                        </a>
                        <a href="{{route('admin.fix_bookings.delete',$fix)}}"
                           class="btn btn-sm btn-clean btn-icon btn-icon-md" title="حذف">
                            <i class="la la-trash text-danger"></i>
                        </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="mt-3">{{$fixBookings->links()}}</div>

    @endcomponent


@endsection